/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import common.Utils;
import dao.StaffDao;
import java.time.LocalDate;
import java.util.List;
import model.Staff;

/**
 *
 * @author Dungpc
 */
public class AddOrEditStaff extends javax.swing.JFrame {

    private int staffId;
    private StaffDao staffDao = StaffDao.getInstance();
    private ManageStaff parentView;

    /**
     * Creates new form Add_new_staff
     */
    public AddOrEditStaff(ManageStaff parentView) {
        this(-1, parentView);
    }

    public AddOrEditStaff(int staffId, ManageStaff parentView) {
        this.staffId = staffId;
        this.parentView = parentView;
        initComponents();
        validateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cbxSex = new javax.swing.JComboBox<>();
        cbxPosition = new javax.swing.JComboBox<>();
        btnAction = new javax.swing.JButton();
        dpStart = new com.toedter.calendar.JDateChooser();
        dpBirthDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        dpEnd = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnAction1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(744, 573));
        setMinimumSize(new java.awt.Dimension(744, 573));
        setPreferredSize(new java.awt.Dimension(744, 573));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 51, 51));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        lblTitle.setText("New Staff");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 102, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sex");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 102, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Birth Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 102, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Position");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 102, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Monthly Salary");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 102, 20));

        lblEndDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEndDate.setForeground(new java.awt.Color(255, 255, 255));
        lblEndDate.setText("End Date");
        getContentPane().add(lblEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 102, 20));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 299, 30));

        txtSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalaryKeyReleased(evt);
            }
        });
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 299, 30));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 299, 30));

        cbxSex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexActionPerformed(evt);
            }
        });
        getContentPane().add(cbxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 299, 30));

        cbxPosition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cbxPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 299, 30));

        btnAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnAction.setText("Save");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 100, 30));

        dpStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpStart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpStartPropertyChange(evt);
            }
        });
        getContentPane().add(dpStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 300, 30));

        dpBirthDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpBirthDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpBirthDatePropertyChange(evt);
            }
        });
        getContentPane().add(dpBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 300, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Start Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 102, 20));

        dpEnd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpEnd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpEndPropertyChange(evt);
            }
        });
        getContentPane().add(dpEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 300, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        btnAction1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAction1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnAction1.setText("Clear");
        btnAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAction1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 100, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1480, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        List.of("Male", "Female").forEach(cbxSex::addItem);
        List.of("Barista", "Server", "Chef", "Manager", "Counter Service", "Shipper").forEach(cbxPosition::addItem);

        if (staffId != -1) {
            lblTitle.setText("Edit Staff");
            lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png")));

            Staff staff = staffDao.getById(staffId);
            txtName.setText(staff.getFullName());
            cbxSex.setSelectedItem(staff.getSex());
            dpBirthDate.setDate(Utils.toDate(staff.getBirthDate()));
            txtPhone.setText(staff.getPhoneNumber());
            cbxPosition.setSelectedItem(staff.getPosition());
            txtSalary.setText("%.2f".formatted(staff.getMonthlySalary()));
            dpStart.setDate(Utils.toDate(staff.getStartDate()));
            dpEnd.setDate(Utils.toDate(staff.getEndDate()));
        } else {
            lblEndDate.setVisible(false);
            dpEnd.setVisible(false);
        }
    }//GEN-LAST:event_formComponentShown

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        validateFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void dpBirthDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpBirthDatePropertyChange
        validateFields();
    }//GEN-LAST:event_dpBirthDatePropertyChange

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        validateFields();
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyReleased
        validateFields();
    }//GEN-LAST:event_txtSalaryKeyReleased

    private void dpStartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpStartPropertyChange
        validateFields();
    }//GEN-LAST:event_dpStartPropertyChange

    private void dpEndPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpEndPropertyChange
        validateFields();
    }//GEN-LAST:event_dpEndPropertyChange

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        Staff staff = new Staff();
        staff.setFullName(txtName.getText());
        staff.setSex((String) cbxSex.getSelectedItem());
        staff.setBirthDate(Utils.toLocalDate(dpBirthDate.getDate()));
        staff.setPhoneNumber(txtPhone.getText());
        staff.setPosition((String) cbxPosition.getSelectedItem());
        staff.setMonthlySalary(Double.parseDouble(txtSalary.getText()));
        staff.setStartDate(Utils.toLocalDate(dpStart.getDate()));
        staff.setEndDate(Utils.toLocalDate(dpEnd.getDate()));

        if (staffId == -1) {
            staffDao.saveStaff(staff);
        } else {
            staff.setId(staffId);
            staffDao.updateStaff(staff);
        }
        setVisible(false);
        parentView.loadStaffList();
    }//GEN-LAST:event_btnActionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAction1ActionPerformed
        txtName.setText("");
        cbxSex.setSelectedIndex(0);
        dpBirthDate.setDate(null);
        txtPhone.setText("");
        cbxPosition.setSelectedIndex(0);
        txtSalary.setText("");
        dpStart.setDate(null);
        dpEnd.setDate(null);
        validateFields();
    }//GEN-LAST:event_btnAction1ActionPerformed

    private void validateFields() {
        LocalDate birthDate = Utils.toLocalDate(dpBirthDate.getDate());
        LocalDate startDate = Utils.toLocalDate(dpStart.getDate());
        LocalDate endDate = Utils.toLocalDate(dpEnd.getDate());
        try {
            double salary = Double.parseDouble(txtSalary.getText());
            if (!txtName.getText().isEmpty()
                    && birthDate != null && birthDate.isBefore(LocalDate.now())
                    && txtPhone.getText().matches("[0-9]{10}")
                    && salary > 0
                    && startDate != null
                    && (endDate == null || (!startDate.isAfter(endDate)))) {
                btnAction.setEnabled(true);
            } else {
                btnAction.setEnabled(false);
            }
        } catch (Exception ex) {
            btnAction.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrEditStaff(1, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnAction1;
    private javax.swing.JComboBox<String> cbxPosition;
    private javax.swing.JComboBox<String> cbxSex;
    private com.toedter.calendar.JDateChooser dpBirthDate;
    private com.toedter.calendar.JDateChooser dpEnd;
    private com.toedter.calendar.JDateChooser dpStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
